Repository nextcloud/files_videoplayer, pull requests merged in 2019-01, with the labels that each got.

#76 Update master php testing versions
  .drone.yml
Labels: 4. to release

#78 Fill screen in fullscreen mode for public videos. Fixes #77
  css/style.css
Labels: 4. to release, backport-request, bug

#80 Move vendored dependencies to npm, build with webpack and babel
  .babelrc
  .gitignore
  appinfo/app.php
  js/main.js
  js/main.js.map
  js/vendors~videojs.js
  js/vendors~videojs.js.map
  js/videojs/font/vjs.eot
  js/videojs/font/vjs.svg
  js/videojs/font/vjs.ttf
  js/videojs/font/vjs.woff
  js/videojs/lang/ar.js
  js/videojs/lang/bg.js
  js/videojs/lang/ca.js
  js/videojs/lang/cs.js
  js/videojs/lang/de.js
  js/videojs/lang/es.js
  js/videojs/lang/fr.js
  js/videojs/lang/hu.js
  js/videojs/lang/it.js
  js/videojs/lang/ja.js
  js/videojs/lang/ko.js
  js/videojs/lang/nl.js
  js/videojs/lang/pt-BR.js
  js/videojs/lang/ru.js
  js/videojs/lang/tr.js
  js/videojs/lang/uk.js
  js/videojs/lang/vi.js
  js/videojs/lang/zh-CN.js
  js/videojs/lang/zh-TW.js
  js/videojs/video-js.css
  js/videojs/video.js
  package-lock.json
  package.json
  src/viewer.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
Labels: 4. to release, enhancement, technical debt

#90 Build/check vue build
  .drone.yml
  js/vendors~videojs.js.map
  package-lock.json
  package.json
Labels: 3. to review

#93 Include css in js bundle
  appinfo/app.php
  js/main.js
  js/main.js.map
  js/vendors~videojs.js
  js/vendors~videojs.js.map
  js/videojs.js
  js/videojs.js.map
  src/viewer.js
  src/webpack.common.js
Labels: enhancement
